name: Build and publish python package

on:
  release:
    types: [ published ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
          
      - name: Build and publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_KEY }}
          poetry publish --build
